GET http://localhost:3000/products
Content-Type: application/json

{
"token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiVGVzdCIsImlhdCI6MTY5OTQzNzg1NH0.fMRoBpzeCTBmkU24RKTABn7rdv641CukeCvK2gNGLQ8"
}
###

PUT http://localhost:3000/products/1
Content-Type: application/json

{
    "title": "Updated Product",
    "price": 19.99,
    "description": "This is an updated product"
}
###
POST http://localhost:3000/products
Content-Type: application/json

{
    "name": "New Product",
    "price": 9.99,
    "description": "This is a new product"
}

###